---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-resource-quotas
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-6 Resource Availability
    policy.open-cluster-management.io/description: |
      Enforce resource quotas and limit ranges to prevent resource exhaustion
      attacks and ensure fair resource allocation across namespaces.
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    # Policy 1: Enforce namespace resource quotas
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-namespace-quota
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            include:
              - "security-demo"
              - "production"
              - "staging"
            exclude:
              - "kube-*"
              - "openshift-*"
              - "default"
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ResourceQuota
                metadata:
                  name: namespace-quota
                spec:
                  hard:
                    requests.cpu: "10"
                    requests.memory: "20Gi"
                    limits.cpu: "20"
                    limits.memory: "40Gi"
                    persistentvolumeclaims: "10"
                    pods: "50"
                    secrets: "100"
                    configmaps: "100"
                    services: "20"
                    services.loadbalancers: "2"
    # Policy 2: Enforce pod limit ranges
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-pod-limit-range
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            include:
              - "security-demo"
              - "production"
              - "staging"
            exclude:
              - "kube-*"
              - "openshift-*"
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: LimitRange
                metadata:
                  name: pod-limit-range
                spec:
                  limits:
                    # Pod limits
                    - type: Pod
                      max:
                        cpu: "4"
                        memory: "8Gi"
                      min:
                        cpu: "10m"
                        memory: "16Mi"
                    # Container limits
                    - type: Container
                      max:
                        cpu: "2"
                        memory: "4Gi"
                      min:
                        cpu: "10m"
                        memory: "16Mi"
                      default:
                        cpu: "100m"
                        memory: "128Mi"
                      defaultRequest:
                        cpu: "50m"
                        memory: "64Mi"
                    # PVC limits
                    - type: PersistentVolumeClaim
                      max:
                        storage: "100Gi"
                      min:
                        storage: "1Gi"
    # Policy 3: Ensure no pods without resource limits
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-require-pod-resources
        spec:
          remediationAction: inform
          severity: high
          namespaceSelector:
            include:
              - "security-demo"
              - "production"
              - "staging"
          object-templates-raw: |
            {{- range (lookup "v1" "Pod" "" "").items }}
            {{- if and (ne .metadata.namespace "kube-system") (ne .metadata.namespace "openshift") }}
            {{- range .spec.containers }}
            {{- if or (not .resources.limits) (not .resources.requests) }}
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  name: {{ $.metadata.name }}
                  namespace: {{ $.metadata.namespace }}
                spec:
                  containers:
                    - name: {{ .name }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
    # Policy 4: Prevent resource hogging with priority classes
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-priority-classes
        spec:
          remediationAction: inform
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: scheduling.k8s.io/v1
                kind: PriorityClass
                metadata:
                  name: low-priority
                value: 100
                globalDefault: false
                description: "Low priority for batch jobs"
            - complianceType: musthave
              objectDefinition:
                apiVersion: scheduling.k8s.io/v1
                kind: PriorityClass
                metadata:
                  name: high-priority
                value: 1000
                globalDefault: false
                description: "High priority for critical workloads"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-resource-quotas
  namespace: default
placementRef:
  name: placement-all-clusters
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-resource-quotas
    kind: Policy
    apiGroup: policy.open-cluster-management.io
