apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-app
  namespace: security-demo
  labels:
    app: secure-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-app
  template:
    metadata:
      labels:
        app: secure-app
    spec:
      serviceAccountName: secure-app-sa
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: app
        image: registry.access.redhat.com/ubi9/ubi-minimal:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo 'Secure application running'; sleep 30; done"]
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secure-app-sa
  namespace: security-demo
---
apiVersion: v1
kind: Service
metadata:
  name: secure-app
  namespace: security-demo
spec:
  selector:
    app: secure-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
